{
    'name': "Hospital Management",
    'version': '14.0.1.0.0',
    'summary': 'Hospital Management Software',
    'sequence': 20,
    'description': """Longer Description""",
    'category': 'Productivity',
    'website': 'http://www.redytec.com',
    'depends': [],
    'data': [],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto:install': False,
}
